source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
pod 'XMPPFramework', '~> 3.6.6'
pod 'AFNetworking','~>3.0'
pod 'MBProgressHUD','~>0.9.2'
pod 'UIBubbleTableView', '~> 0.2'  
xcodeproj 'XMPP.xcodeproj'
